In [116]:
import pandas as pd
import numpy as np

In [117]:
pd.__version__

'1.5.3'

In [118]:
df = pd.read_csv("/home/cacaprog/learning-projects/ml-zoomcamp/data/housing.csv")

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [120]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [121]:
mhv_near_bay = df['median_house_value'].where(df['ocean_proximity'] == 'NEAR BAY')


In [122]:
mhv_near_bay.mean()

259212.31179039303

In [123]:
avg_total_bedrooms = df['total_bedrooms'].mean()
avg_total_bedrooms

537.8705525375618

In [124]:
avg_total_bedrooms = df['total_bedrooms'].fillna(537.8705525375618)
avg_total_bedrooms.mean()

537.8705525375617

In [125]:
X = np.array(df[['housing_median_age', 'total_rooms', 'total_bedrooms']].where(df['ocean_proximity'] == 'ISLAND'))

In [126]:
df[df['ocean_proximity'] == 'ISLAND']

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [127]:
new_df = df[df['ocean_proximity'] == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [128]:
new_df

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [129]:
X = np.array(new_df)

In [130]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [131]:
X_transpose = X.T

In [132]:
# or X_transpose.dot(X)
XTX = X_transpose @ X

In [133]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [134]:
XTX_inverse = np.linalg.inv(XTX)

In [135]:
y = np.array([950, 1300, 800, 1000, 1300])

In [136]:
y

array([ 950, 1300,  800, 1000, 1300])